### ISSUE TITLE
Server Fails to load world, sometimes...

### ISSUE THREAD

**Issue by tysonstrange** [Pryaxis/TSAPI#37]
Occasionally my world filles will just no longer load in TerrariaServer, but will have been used on the server for days.

I've found the world files still open in the vanilla TerrariaServer and/or in TEdit no problem.

After investigation and adding some debug code into the World Loading section of TSAPI I've found the following.

The following function throwing a null reference exception:
CheckWaterDeath(Tile checkTile) line 1561
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.ObjectData.TileObjectData.GetTileData(Tile getTile) in C:\Users\tyson\Dropbox\Documents\Terraria tShock\Projects\TShock-general-devel\TerrariaServerAPI\Terraria\ObjectData\TileObjectData.cs:line 1716
   at Terraria.ObjectData.TileObjectData.CheckWaterDeath(Tile checkTile) in C:\Users\tyson\Dropbox\Documents\Terraria tShock\Projects\TShock-general-devel\TerrariaServerAPI\Terraria\ObjectData\TileObjectData.cs:line 1569

This function is used inside the WaterCheck() function in WorldGen.cs , which is used twice inside the loadWorld() function in WorldFile.cs

Not sure why this is happening, as Vanilla TerrariaServer loads the world fine, like i mentioned.

Here is a copy of one of my world files that stopped working for you to have a look at: http://vps.tls.id.au/broken.wld

Putting the following inside the loop helped track down which x,y tile it was breaking on:
Main.statusText = "X " + i + " Y " + j;

I concluded in this world file that it throws the exception on 6126, 726 which appears to be a Tall Gate (like a wooden door, but 1  block talker). Why it throws the null reference I have no idea, but would like some assistance trying to resolve this issue.

A workaround can be to load the world in vanilla, go to that pos and just smash that 1 tile and it will load again in this TSAPI

**Comment by tysonstrange** [comment]
Further that, I'll note that if try and catch CheckWaterDeath() it will throw the exception on 6126 and 726 and the 4 tiles up, as well as 6144 and 726 and the 4 tiles above...

It seems to be throwing this exception on both of the gates in this house and smashing the gates allows the world to then load fine.

furthermore, with the try and catch in place, smashing that gate in game will throw the excpetion too.
